# Generated by Django 2.2.6 on 2023-04-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettype",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, editable=False, help_text="The number of actual tickets available upon creation"
            ),
        ),
    ]
